name: Web Lint

on:
  push:
    branches: [ main, develop, feature/lint ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.14

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd web
        yarn install --production=false
    - name: Lint
      run: |
        pwd
        cd web
        node_modules/.bin/eslint --ext .jsx .
    - name: Check Formatting
      run: |
        cd web
        node_modules/.bin/prettier --check .
